name: Matrix demo
on:
  push:
    branches:
      - main
jobs:

  build:
    contnue-on-error: true
    strategy: 
      matrix:
        node-versions: [12,14,18]
        os-configs: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os-configs }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-versions}}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'      
        run: npm ci


