name: reusable workflow
on: 
  workflow_call:
    inputs:
     artifact-name: 
      description: name of the deployable artifact
      required: false
      default: dist
      type: string
    # secrets:
    #   secret_name: 
          # required: true
    outputs:
      result: 
        descrption: result of deployment operation
        value: ${{jobs.outputs.outcome}}

jobs:
  deploy:
    outputs: 
      outcome: ${{steps.step_result.outputs.step-res}}
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}
      - name: list files
        run: ls
      - name : output information
        run: |
          echo "deploying reusable workflow"
      - name: set result o/p
        id: step_result
        run: |
          echo "step-res = success" >>$GITHUB_OUTPUT